def create_tables(c):
    c.execute("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT)")
    c.execute("CREATE TABLE IF NOT EXISTS progress (video_id TEXT PRIMARY KEY, progress_idx INTEGER)")
    c.execute("CREATE TABLE IF NOT EXISTS part_stats (video_id TEXT, part_idx INTEGER, wpm INTEGER, acc INTEGER, PRIMARY KEY (video_id, part_idx))")
    c.execute("CREATE TABLE IF NOT EXISTS part_stats_history (id INTEGER PRIMARY KEY AUTOINCREMENT, video_id TEXT, part_idx INTEGER, timestamp INTEGER, wpm INTEGER, acc INTEGER)")
    c.execute("CREATE TABLE IF NOT EXISTS instant_stats (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp INTEGER, wpm INTEGER, rawWpm INTEGER, acc INTEGER, consistency INTEGER, timeMs INTEGER, correctChars INTEGER, wrongChars INTEGER, extraChars INTEGER, missedChars INTEGER, totalKeystrokes INTEGER, isValid INTEGER DEFAULT 1, validationFlags TEXT DEFAULT '')")
    c.execute("CREATE TABLE IF NOT EXISTS video_sessions (session_id TEXT PRIMARY KEY, video_id TEXT, status TEXT, started_at INTEGER, completed_at INTEGER, total_wpm INTEGER, total_acc INTEGER)")
    c.execute("CREATE TABLE IF NOT EXISTS video_session_parts (session_id TEXT, part_idx INTEGER, correct_words INTEGER, total_time_ms INTEGER, total_keys INTEGER, correct_keys INTEGER, mistakes INTEGER DEFAULT 0, pages_completed INTEGER DEFAULT 0, PRIMARY KEY (session_id, part_idx))")
    c.execute("CREATE TABLE IF NOT EXISTS video_page_states (session_id TEXT, part_idx INTEGER, page_idx INTEGER, current_index INTEGER DEFAULT 0, correctness_json TEXT, completed_words INTEGER DEFAULT 0, time_spent_ms INTEGER DEFAULT 0, keys_total INTEGER DEFAULT 0, keys_correct INTEGER DEFAULT 0, keys_wrong INTEGER DEFAULT 0, mistakes INTEGER DEFAULT 0, page_chars_correct INTEGER DEFAULT 0, page_chars_wrong INTEGER DEFAULT 0, page_keystrokes_total INTEGER DEFAULT 0, page_keystrokes_correct INTEGER DEFAULT 0, page_keystrokes_wrong INTEGER DEFAULT 0, last_updated INTEGER, PRIMARY KEY (session_id, part_idx, page_idx))")
    c.execute("CREATE TABLE IF NOT EXISTS playlists (playlist_id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)")
    c.execute("CREATE TABLE IF NOT EXISTS playlist_videos (playlist_id TEXT NOT NULL, video_id TEXT NOT NULL, position INTEGER DEFAULT 0, added_at INTEGER NOT NULL, PRIMARY KEY (playlist_id, video_id))")
    c.execute("CREATE TABLE IF NOT EXISTS learn_dictionary (id INTEGER PRIMARY KEY AUTOINCREMENT, word TEXT NOT NULL UNIQUE, chars TEXT NOT NULL, kars TEXT NOT NULL, folas TEXT NOT NULL, has_juktakkhor BOOLEAN NOT NULL, length INTEGER NOT NULL, source TEXT DEFAULT 'user')")
    c.execute("CREATE TABLE IF NOT EXISTS processed_words_files (file_path TEXT PRIMARY KEY, last_modified REAL, word_count INTEGER)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_learn_len ON learn_dictionary(length)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_learn_jukta ON learn_dictionary(has_juktakkhor)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_video_sessions_video_status_started ON video_sessions(video_id, status, started_at DESC)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_video_sessions_status_completed ON video_sessions(status, completed_at DESC)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_video_sessions_video_status_wpm ON video_sessions(video_id, status, total_wpm DESC)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_part_stats_history_timestamp ON part_stats_history(timestamp)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_part_stats_history_video_part_timestamp ON part_stats_history(video_id, part_idx, timestamp DESC)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_playlists_updated_at ON playlists(updated_at DESC)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_playlist_videos_playlist_position ON playlist_videos(playlist_id, position)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_instant_stats_timestamp ON instant_stats(timestamp)")
