#!/usr/bin/env python3
import os
import sys
import json
import shutil
import logging
import tarfile
import subprocess
import urllib.request
from pathlib import Path

# Configure structured logging
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s: %(message)s",
    datefmt="%H:%M:%S",
)

# Robust path resolution, avoiding any hardcoded directories
PROJECT_ROOT = Path(__file__).resolve().parent
SRC_TAURI = PROJECT_ROOT / "src-tauri"
DIST_DIR = PROJECT_ROOT / "dist"
SERVER_DIR = SRC_TAURI / "server"


def get_rust_target() -> str:
    """Dynamically retrieve the host Rust target triple."""
    logging.info("Detecting Rust target triple...")
    result = subprocess.run(
        ["rustc", "-vV"], capture_output=True, text=True, check=True
    )
    for line in result.stdout.splitlines():
        if line.startswith("host:"):
            target = line.split(" ")[1].strip()
            logging.info(f"Target detected: {target}")
            return target
    raise RuntimeError("Could not determine Rust host target")


def get_app_info() -> tuple[str, str, str]:
    """Extract app name and version dynamically from Tauri config."""
    tauri_conf_path = SRC_TAURI / "tauri.conf.json"
    with open(tauri_conf_path, "r", encoding="utf-8") as f:
        conf = json.load(f)

    raw_name = conf.get("productName", "App")
    name = raw_name.lower().replace(" ", "-")
    version = conf.get("version", "1.0.0")
    return name, raw_name, version


def run_command(
    cmd: list[str],
    cwd: Path | None = None,
    env: dict | None = None,
    capture_output=False,
) -> subprocess.CompletedProcess:
    """Run a shell command with strict error handling."""
    logging.info(f"Executing: {' '.join(str(c) for c in cmd)}")
    try:
        return subprocess.run(
            cmd, cwd=cwd, env=env, check=True, text=True, capture_output=capture_output
        )
    except subprocess.CalledProcessError as e:
        logging.error(
            f"Command failed with exit code {e.returncode}: {' '.join(str(c) for c in cmd)}"
        )
        if capture_output and e.stderr:
            logging.error(f"Error output: {e.stderr}")
        sys.exit(e.returncode)


def validate_environment() -> None:
    """Ensure all required build tools and directories exist."""
    required_tools = ["rustc", "cargo", sys.executable]
    for tool in required_tools:
        if not shutil.which(tool):
            logging.error(f"Missing required build tool: {tool}")
            sys.exit(1)

    # Check for npm
    if not shutil.which("npm"):
        logging.error("npm is not installed. Please install Node.js.")
        sys.exit(1)


def build_sidecar(target_triple: str, app_name: str) -> None:
    """Compile the Python backend into a standalone binary."""
    logging.info("--- Building Python Backend (Sidecar) ---")

    SERVER_DIR.mkdir(parents=True, exist_ok=True)

    # Tauri expects sidecars to have the exact target triple suffix
    sidecar_base_name = f"{app_name}-server"
    exe_ext = ".exe" if sys.platform == "win32" else ""
    sidecar_filename = f"{sidecar_base_name}-{target_triple}{exe_ext}"

    # Identify extra data directories automatically
    data_args = []
    for d in ["app", "scripts", "static"]:
        if (PROJECT_ROOT / d).exists():
            separator = ";" if sys.platform == "win32" else ":"
            data_args.extend(["--add-data", f"{d}{separator}{d}"])

    # Clean up previous pyinstaller artifacts to prevent stale builds
    for d in ["build", "dist"]:
        path = PROJECT_ROOT / d
        if path.exists():
            shutil.rmtree(path)

    # Compile with PyInstaller
    cmd = (
        [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--onefile",
            "--name",
            sidecar_base_name,
            "--hidden-import",
            "uvicorn",
            "--hidden-import",
            "fastapi",
        ]
        + data_args
        + ["sidecar.py"]
    )

    run_command(cmd, cwd=PROJECT_ROOT)

    # Relocate the binary to where Tauri expects it
    built_bin = PROJECT_ROOT / "dist" / f"{sidecar_base_name}{exe_ext}"
    dest_bin = SERVER_DIR / sidecar_filename

    if built_bin.exists():
        shutil.move(built_bin, dest_bin)
        dest_bin.chmod(0o755)
        logging.info(f"Successfully compiled backend into: {dest_bin}")
    else:
        logging.error("Backend binary was not generated by PyInstaller.")
        sys.exit(1)

    # Clean the dist directory created by pyinstaller to prepare for final outputs
    shutil.rmtree(PROJECT_ROOT / "dist", ignore_errors=True)


def build_tauri() -> None:
    """Build the final Tauri application."""
    logging.info("--- Building Frontend & Bundling Tauri App ---")

    npx_cmd = shutil.which("npx")
    if not npx_cmd:
        logging.error("npx is not installed or not in PATH.")
        sys.exit(1)

    # Set safe bundle targets per platform to prevent failures
    bundles = "deb,rpm" if sys.platform == "linux" else "msi,nsis"

    # Use npx directly as it passes arguments strictly and without shell interference
    cmd = [npx_cmd, "tauri", "build", "--bundles", bundles]
    run_command(cmd, cwd=PROJECT_ROOT)


def build_appimage_manual(app_name: str, raw_name: str, version: str) -> None:
    """Manually build an AppImage without using Tauri's internal linuxdeploy (which frequently fails on modern distros)."""
    if sys.platform != "linux":
        return

    logging.info("--- Building AppImage Manually ---")

    target_bin = SRC_TAURI / "target" / "release" / app_name
    if not target_bin.exists():
        logging.error("Tauri binary not found, skipping AppImage build.")
        return

    appimagetool_path = PROJECT_ROOT / "appimagetool"
    if not shutil.which("appimagetool") and not appimagetool_path.exists():
        logging.info("Downloading appimagetool...")
        url = "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        try:
            urllib.request.urlretrieve(url, appimagetool_path)
            appimagetool_path.chmod(0o755)
        except Exception as e:
            logging.error(f"Failed to download appimagetool: {e}")
            return

    tool_cmd = (
        ["appimagetool"] if shutil.which("appimagetool") else [str(appimagetool_path)]
    )

    # Assemble AppDir
    appdir = PROJECT_ROOT / "AppDir"
    if appdir.exists():
        shutil.rmtree(appdir)

    bin_dir = appdir / "usr" / "bin"
    apps_dir = appdir / "usr" / "share" / "applications"
    icons_dir = appdir / "usr" / "share" / "icons" / "hicolor" / "scalable" / "apps"

    for d in [bin_dir, apps_dir, icons_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # Copy main binary and sidecar
    shutil.copy2(target_bin, bin_dir / app_name)
    (bin_dir / app_name).chmod(0o755)

    for f in SERVER_DIR.iterdir():
        if f.is_file() and f.name.startswith(f"{app_name}-server"):
            dest_sidecar = bin_dir / f"{app_name}-server"
            shutil.copy2(f, dest_sidecar)
            dest_sidecar.chmod(0o755)

    # Desktop and Icons
    icon_src = SRC_TAURI / "icons" / "icon.svg"
    if icon_src.exists():
        shutil.copy2(icon_src, icons_dir / f"{app_name}.svg")
        shutil.copy2(icon_src, appdir / f"{app_name}.svg")

    desktop_file = f"""[Desktop Entry]
Name={raw_name}
Exec={app_name}
Icon={app_name}
Terminal=false
Type=Application
Categories=Utility;
"""
    (apps_dir / f"{app_name}.desktop").write_text(desktop_file)
    (appdir / f"{app_name}.desktop").write_text(desktop_file)

    # AppRun symlink
    apprun = appdir / "AppRun"
    apprun.symlink_to(f"usr/bin/{app_name}")

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    out_file = DIST_DIR / f"{app_name}-{version}-x86_64.AppImage"

    try:
        # Run appimagetool and point APPIMAGE_EXTRACT_AND_RUN just in case we are in docker
        env = os.environ.copy()
        env["APPIMAGE_EXTRACT_AND_RUN"] = "1"
        run_command(
            tool_cmd + ["--no-appstream", str(appdir), str(out_file)],
            cwd=PROJECT_ROOT,
            env=env,
            capture_output=True,
        )
        logging.info(f"AppImage generated successfully: {out_file.name}")
    except Exception as e:
        logging.error(f"Failed to compile final AppImage: {e}")
    finally:
        shutil.rmtree(appdir, ignore_errors=True)


def collect_artifacts(app_name: str, version: str) -> None:
    """Gather all final distribution packages into the cleanly prepared dist directory."""
    logging.info("--- Collecting Build Artifacts ---")

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    bundle_dir = SRC_TAURI / "target" / "release" / "bundle"

    collected_files = []

    if bundle_dir.exists():
        # 1. Collect standard installers and bundles generated by Tauri
        for ext in ["*.deb", "*.rpm", "*.msi", "*.exe"]:
            for file_path in bundle_dir.rglob(ext):
                dest = DIST_DIR / file_path.name
                shutil.copy2(file_path, dest)
                collected_files.append(dest)
    else:
        logging.warning(
            "Tauri bundle directory not found. Standard installers were not generated."
        )

    # 2. Collect AppImage if it was generated
    for appimage in DIST_DIR.glob("*.AppImage"):
        collected_files.append(appimage)

    # 3. Create a generic portable tarball for Linux/macOS containing the raw binaries
    target_bin = SRC_TAURI / "target" / "release" / app_name
    if target_bin.exists() and sys.platform != "win32":
        portable_name = f"{app_name}-{version}-portable.tar.gz"
        portable_path = DIST_DIR / portable_name

        with tarfile.open(portable_path, "w:gz") as tar:
            # Add main executable
            tar.add(target_bin, arcname=f"{app_name}-{version}/{app_name}")

            # Add companion sidecar binary
            for f in SERVER_DIR.iterdir():
                if f.is_file() and f.name.startswith(f"{app_name}-server"):
                    tar.add(f, arcname=f"{app_name}-{version}/{f.name}")

        if portable_path not in collected_files:
            collected_files.append(portable_path)

    # Report results
    if collected_files:
        logging.info("Distribution ready! Artifacts located in 'dist/':")
        for item in set(collected_files):
            size_mb = item.stat().st_size / (1024 * 1024)
            logging.info(f"  - {item.name} ({size_mb:.1f} MB)")
    else:
        logging.warning("No build artifacts found.")


def main() -> None:
    try:
        logging.info("Starting production build process...")

        # Validation & Setup
        validate_environment()
        app_name, raw_name, version = get_app_info()
        target_triple = get_rust_target()

        # Build Pipeline
        build_sidecar(target_triple, app_name)
        build_tauri()
        build_appimage_manual(app_name, raw_name, version)
        collect_artifacts(app_name, version)

        logging.info("Build pipeline completed successfully.")

    except KeyboardInterrupt:
        logging.warning("Build canceled by user.")
        sys.exit(1)
    except Exception as e:
        logging.error(f"Fatal error during build: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
